### ISSUE TITLE
Angular build error using pixels lib

### ISSUE THREAD

**Issue by SteinSmeets** [PacoteJS/pacote#39]
Sudden error while building project.

ERROR in ./node_modules/@pacote/get-style/lib/esm/index.js 2:39
Module parse failed: Unexpected token (2:39)
File was processed with these loaders:
  ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js
You may need an additional loader to handle the result of these loaders.
> export function getStyle(element, property) {
>     ---> const view = element.ownerDocument?.defaultView || window;
>    const style = view.getComputedStyle(element);
>    return (style.getPropertyValue(property) || style[property]);
 @ ./node_modules/@pacote/pixels/lib/esm/index.js 1:0-45 8:10-18 9:10-18

node: 12.18.2
npm: 6.14.5
Angular: 9.x.x

**Comment by goblindegook** [comment]
You likely need to configure that Webpack loader to handle optional chaining. If your main project already supports it, you can force Webpack to transpile the `@pacote/get-style` module (since the modules in `node_modules` are normally excluded from transpilation).

**Comment by SteinSmeets** [comment]
Thanks @goblindegook 
Seems like optional chaining is not supported in webpack 4 ( which is the one angular-cli is using now). 

Typescript version: 3.8.3

**Comment by goblindegook** [comment]
I'm not familiar with Angular tooling, unfortunately, but you should be able to configure Webpack in order to resolve the issue in one of these two ways:

* Use module resolution configuration to import the plain ECMAScript 5 build of this module. (By default, Webpack will prioritise loading the `module` entry over `main`.) If you can't change that, you might still be able to create an alias pointing to the right file under `node_modules`.

* Allow the module to be transpiled by whatever loader is being used by Webpack (Babel? TS?). If you already have something like `exclude: /node_modules/` in there, try `exclude: /node_modules\/(?!@pacote\/pixels)/`.

**Comment by goblindegook** [comment]
I've enabled ES2019 exports for the time being, as Webpack versions prior to 5 seem to struggle with modern language features like nullish coalescence and optional chaining. Hopefully the latest version should work for you.
